// <auto-generated />
using System;
using EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200416091335_Add_Seed_Data")]
    partial class Add_Seed_Data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Age = 27,
                            Created = new DateTime(2020, 4, 16, 12, 13, 34, 841, DateTimeKind.Local).AddTicks(4524),
                            FirstName = "John",
                            LastName = "Gold",
                            Modified = new DateTime(2020, 4, 16, 12, 13, 34, 844, DateTimeKind.Local).AddTicks(8951)
                        },
                        new
                        {
                            Id = 2L,
                            Age = 16,
                            Created = new DateTime(2020, 4, 16, 12, 13, 34, 845, DateTimeKind.Local).AddTicks(126),
                            FirstName = "Ronald",
                            LastName = "Weasley",
                            Modified = new DateTime(2020, 4, 16, 12, 13, 34, 845, DateTimeKind.Local).AddTicks(172)
                        },
                        new
                        {
                            Id = 3L,
                            Age = 18,
                            Created = new DateTime(2020, 4, 16, 12, 13, 34, 845, DateTimeKind.Local).AddTicks(199),
                            FirstName = "Sherlock ",
                            LastName = "Holmes",
                            Modified = new DateTime(2020, 4, 16, 12, 13, 34, 845, DateTimeKind.Local).AddTicks(206)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
